site_name: HedgeDoc
site_url: https://docs.hedgedoc.org
repo_url: https://github.com/hedgedoc/hedgedoc
site_description: 'HedgeDoc Documentation'
site_author: 'HedgeDoc Developers'
docs_dir: content
edit_uri: https://github.com/hedgedoc/hedgedoc/edit/master/docs/content/
nav:
  - Home: index.md
  - Installation:
      - 'Manual Installation': setup/manual-setup.md
      - 'Reverse Proxy': setup/reverse-proxy.md
      - Docker: setup/docker.md
      - Cloudron: setup/cloudron.md
      - Heroku: setup/heroku.md
      - LinuxServer: setup/docker-linuxserver.md
      - Yunohost: setup/yunohost.md
  - Guides:
      - Authentication:
          - LDAP: guides/auth/ldap-ad.md
          - OAuth: guides/auth/oauth.md
          - SAML: guides/auth/saml.md
          - SAML Keycloak: guides/auth/saml-keycloak.md
          - SAML OneLogin: guides/auth/saml-onelogin.md
          - GitHub: guides/auth/github.md
          - GitLab: guides/auth/gitlab-self-hosted.md
          - Keycloak: guides/auth/keycloak.md
          - Nextcloud: guides/auth/nextcloud.md
          - Twitter: guides/auth/twitter.md
      - Media Backend:
          - MinIO: guides/minio-image-upload.md
          - S3: guides/s3-image-upload.md
      - Migrate from Etherpad: guides/migrate-etherpad.md
      - Breaking Changes: guides/migrations-and-breaking-changes.md
      - Terms of Use Setup: guides/providing-terms.md
  - Configuration: configuration.md
  - Developer:
      - 'Getting Started': dev/getting-started.md
      - API: dev/api.md
      - 'Operational Transformation': dev/ot.md
      - Webpack: dev/webpack.md
      - 'Documentation': dev/documentation.md
  - FAQ: https://hedgedoc.org/faq
markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
  - mdx_truly_sane_lists
theme:
  name: 'material'
  language: en
  favicon: images/favicon.png
  logo: images/logo.svg
  palette:
    scheme: light
    primary: 'hedgedoc'
    accent: 'hedgedoc'
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
  font: false

extra_css:
  - theme/styles/hedgedoc-custom.css
  - theme/styles/roboto.css
